version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:yourpassword@postgres:5432/yourdatabase"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: [ "sh", "-c", "npx prisma migrate deploy && npm start" ]

volumes:
  postgres-data:
