version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DB1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:pass123@postgres:5432/DB1"
    ports:
      - "3000:3000"
      - "5555:5555"
      
    depends_on:
      - postgres
    command: [ "sh", "-c", "npx prisma migrate deploy && npm start" ]

volumes:
  postgres-data:
